name: Tester

on: [push]

jobs:
  check-versions:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - name: Run create-output.sh file
      run: chmod 755 create-output.sh; ./create-output.sh
      
    - name: clang++ version
      run: clang++ --version
      
    - name: clang-format version
      run: clang-format --version
      
    - name: install clang-tidy
      run: sudo apt-get install --yes --quiet clang=tidy
      
    - name: clang-tidy version
      run: clang-tidy --version
        



            


