name: Docker Setup

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Run create-output.sh file
      run: ./docker-setup.sh
